# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 平行链
email: parallelchain@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  关于区块链各种问题的观点。 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://parallelchain.github.io" # the base hostname & protocol for your site
twitter_username: parallelchain 
github_username:  parallelchain 

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
